import { Component, OnInit } from '@angular/core';
import { FirestoreDatabaseService } from 'src/app/shared/services/firebase/firestoreDatabase/firestore-database.service';
import { UUID } from 'angular2-uuid';

@Component({
  selector: 'app-admin-landing',
  templateUrl: './admin-landing.component.html',
  styleUrls: ['./admin-landing.component.css']
})
export class AdminLandingComponent implements OnInit {

  constructor(
    private firestoreDB: FirestoreDatabaseService
  ) { }

  ngOnInit() {
  }

  /*
    const videoData = {
      videoID: docKey,
      isSeries: true,
      isActive: true,
      name: '',
      description: '',
      URL: {
        thumbnail: '',
        video: ''
      },
      addedOn: Date.now(),
      views: 0,
      sortOrder: 0,
      addedBy: '',
      likes: 0,
      genre: '',
      episode: [{
        videoID: '',
        name: '',
        description: '',
        URL: {
          thumbnail: '',
          video: ''
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 0,
        addedBy: '',
        likes: 0
      }]
    };
  */

 dummyButton() {
    const uuid = UUID.UUID();
    console.log('Auto generated--> ', uuid);
  //  this.firestoreDB.createNewVideoPlaylist(uuid);
 }

  createVideo() {
    // const autogeneratedID = UUID.UUID();
    const videoData = {
      videoID: UUID.UUID(),
      isSeries: true,
      isActive: true,
      name: 'Boston Dynamics',
      description: 'Boston Dynamics is an American engineering and robotics design company founded in 1992 as a spin-off from the Massachusetts Institute of Technology.',
      URL: {
        thumbnail: 'https://img.youtube.com/vi/LikxFZZO2sk/0.jpg',
        video: 'https://www.youtube.com/watch?v=LikxFZZO2sk'
      },
      addedOn: Date.now(),
      views: 0,
      sortOrder: 0,
      addedBy: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
      likes: 0,
      genre: 'Science & Technology',
      episode: [{
        videoID: UUID.UUID(),
        name: 'UpTown Spot',
        description: 'This Clip Of Boston Dynamics Spot Dancing To Uptown Funk',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/kHBcVlqpvZ8/0.jpg',
          video: 'https://www.youtube.com/watch?v=kHBcVlqpvZ8'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 0,
        addedBy: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        likes: 0
      },
      {
        videoID: UUID.UUID(),
        name: 'The New SpotMini',
        description: 'SpotMini is a new smaller version of the Spot robot, weighing 55 lbs dripping wet (65 lbs if you include its arm.)  SpotMini is all-electric (no hydraulics) and runs for about 90 minutes on a charge, depending on what it is doing.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/kgaO45SyaO4/0.jpg',
          video: 'https://www.youtube.com/watch?v=kgaO45SyaO4'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 1,
        addedBy: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        likes: 0
      },
      {
        videoID: UUID.UUID(),
        name: 'Atlas, The Next Generation',
        description: 'A new version of Atlas, designed to operate outdoors and inside buildings. It is specialized for mobile manipulation. It is electrically powered and hydraulically actuated.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/rVlhMGQgDkY/0.jpg',
          video: 'https://www.youtube.com/watch?v=rVlhMGQgDkY'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 2,
        addedBy: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        likes: 0
      }
    ]
    };
    console.log(videoData);
    this.firestoreDB.createNewVideoPlaylist(videoData);
  }
}
