import { Component, OnInit } from '@angular/core';
import { FirestoreDatabaseService } from 'src/app/shared/services/firebase/firestoreDatabase/firestore-database.service';
import { UUID } from 'angular2-uuid';

@Component({
  selector: 'app-admin-landing',
  templateUrl: './admin-landing.component.html',
  styleUrls: ['./admin-landing.component.css']
})
export class AdminLandingComponent implements OnInit {

  constructor(
    private firestoreDB: FirestoreDatabaseService
  ) { }

  ngOnInit() {
  }

  /*
    const autogeneratedID = Date.now().toString();
    const videoData = {
      videoID: autogeneratedID,
      isSeries: true,
      isActive: true,
      name: '',
      description: '',
      URL: {
        thumbnail: '',
        video: ''
      },
      addedOn: Date.now(),
      views: 0,
      sortOrder: 0,
      addedBy: {
        uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        name: 'Amitabh Sharma'
      },
      likes: 0,
      genre: '',
      episode: [{
        videoID:  autogeneratedID + '-0',
        name: '',
        description: '',
        URL: {
          thumbnail: '',
          video: ''
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 0,
        addedBy: {
        uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        name: 'Amitabh Sharma'
      },
        likes: 0
      }]
    };
  */

  dummyButton() {
    const uuid = UUID.UUID();
    console.log('Auto generated--> ', uuid);
    //  this.firestoreDB.createNewVideoPlaylist(uuid);
  }

  createVideo() {
    const autogeneratedID = Date.now().toString();
    const videoData = {
      videoID: autogeneratedID,
      isSeries: true,
      isActive: true,
      name: 'High Altitude Warfare School | Veer by Discovery',
      description: 'High Altitude Warfare School. Watch the true story of Indian Army Mountain Warriors training to defend the highest battlefield in the world. ',
      URL: {
        thumbnail: 'https://img.youtube.com/vi/rAtJ9PoZ8ng/maxresdefault.jpg',
        video: 'https://www.youtube.com/watch?v=rAtJ9PoZ8ng'
      },
      addedOn: Date.now(),
      views: 0,
      sortOrder: 1,
      addedBy: {
        uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        name: 'Amitabh Sharma'
      },
      likes: {
        likes: 0,
        likedBy: []
      },
      genre: 'People & Blogs',
      episode: [{
        videoID: autogeneratedID + '-0',
        name: 'Introduction to High Altitude Warfare School | HAWS E1P1 | Veer by Discovery',
        description: 'The first week of training entails a small walk of about 1.5 km with a little load on one’s back, which soon progresses to 5, 10 and 15 kilograms after two weeks, even as the distance increases and soldiers are introduced to tougher levels.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/bEI7jySEUyQ/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=bEI7jySEUyQ'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 0,
        addedBy: {
          uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
          name: 'Amitabh Sharma'
        },
        likes: {
          likes: 0,
          likedBy: []
        },
      },
      {
        videoID: autogeneratedID + '-1',
        name: 'Mountain Survival Training for Indian Army Soldiers | HAWS E1P2 | Veer by Discovery',
        description: 'Selected Indian Army personnel are trained at HAWS to become mountain warriors. In the initial training, soldiers have to stay in the forest at survival top which is at a height of 10,500 feet. They are trained for survival instincts in bad weather conditions, freezing temperature and low level of oxygen.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/aOOmLTV_Oz8/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=aOOmLTV_Oz8'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 1,
        addedBy: {
          uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
          name: 'Amitabh Sharma'
        },
        likes: {
          likes: 0,
          likedBy: []
        },
      },
      {
        videoID: autogeneratedID + '-2',
        name: 'Stream Crossing Training at High Altitude Warfare School | HAWS E1P3 | Veer by Discovery',
        description: 'During the 72 hours of mountain survival training at High Altitude Warfare School (HAWS) soldiers are trained for combat situations where they have to cross rapid currents of river virtually unaided. Watch India’s fiercest mountain warriors crossing the river stream within minutes. They are among the top instructors at HAWS, representing the nation at the International Army Games of Elbrus in Russia.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/elZiT2RIpFY/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=elZiT2RIpFY'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 2,
        addedBy: {
          uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
          name: 'Amitabh Sharma'
        },
        likes: {
          likes: 0,
          likedBy: []
        },
      },
      {
        videoID: autogeneratedID + '-3',
        name: 'Endurance Run at 9000 Feet | High Altitude Warfare School E1P4 | Veer by Discovery',
        description: 'The Endurance Run at High Altitude Warfare School is an 18km long run in tough terrains with the finish line at a height of 9000 feet. It\'s a mental challenge and endurance test for trainee soldiers at HAWS to run with 18kg of battle load along with their personal weapons. Will they clear the litmus test for the toughest job in the world: defending India’s Himalayan borders. Watch this episode to find out.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/RdFYHrBo5rY/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=RdFYHrBo5rY'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 3,
        addedBy: {
          uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
          name: 'Amitabh Sharma'
        },
        likes: {
          likes: 0,
          likedBy: []
        },
      },
      {
        videoID: autogeneratedID + '-4',
        name: 'Endurance Test: Making of Mountain Warriors | High Altitude Warfare School E1P5 | Veer by Discovery',
        description: 'The Endurance Run at High Altitude Warfare School is an 18km long run in tough terrains with the finish line at a height of 9000 feet. It\'s a mental challenge and endurance test for trainee soldiers at HAWS to run with 18kg of battle load along with their personal weapons. Will they clear the litmus test for the toughest job in the world: defending India’s Himalayan borders. Watch this episode to find out.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/TB_2e-ydGOI/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=TB_2e-ydGOI'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 4,
        addedBy: {
          uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
          name: 'Amitabh Sharma'
        },
        likes: {
          likes: 0,
          likedBy: []
        },
      }
      ]
    };
    console.log(videoData);
    this.firestoreDB.createNewVideoPlaylist(videoData)
      .then((response: any) => {
        if (!response.error) {
          console.log('Created new playlist');
        }
      }).catch((error) => {
        console.log('Error----> ', error);
      });
  }
}



/*
    const autogeneratedID = Date.now().toString();
    const videoData = {
      videoID: autogeneratedID,
      isSeries: true,
      isActive: true,
      name: 'Boston Dynamics',
      description: 'Boston Dynamics is an American engineering and robotics design company founded in 1992 as a spin-off from the Massachusetts Institute of Technology.',
      URL: {
        thumbnail: 'https://img.youtube.com/vi/LikxFZZO2sk/maxresdefault.jpg',
        video: 'https://www.youtube.com/watch?v=LikxFZZO2sk'
      },
      addedOn: Date.now(),
      views: 0,
      sortOrder: 0,
      addedBy: {
        uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        name: 'Amitabh Sharma'
      },
      likes: 0,
      genre: 'Science & Technology',
      episode: [{
        videoID: autogeneratedID + '-0',
        name: 'UpTown Spot',
        description: 'This Clip Of Boston Dynamics Spot Dancing To Uptown Funk',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/kHBcVlqpvZ8/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=kHBcVlqpvZ8'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 0,
        addedBy: {
          uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
          name: 'Amitabh Sharma'
        },
        likes: 0
      },
      {
        videoID: autogeneratedID + '-1',
        name: 'The New SpotMini',
        description: 'SpotMini is a new smaller version of the Spot robot, weighing 55 lbs dripping wet (65 lbs if you include its arm.)  SpotMini is all-electric (no hydraulics) and runs for about 90 minutes on a charge, depending on what it is doing.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/kgaO45SyaO4/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=kgaO45SyaO4'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 1,
        addedBy: {
          uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
          name: 'Amitabh Sharma'
        },
        likes: 0
      },
      {
        videoID: autogeneratedID + '-2',
        name: 'Atlas, The Next Generation',
        description: 'A new version of Atlas, designed to operate outdoors and inside buildings. It is specialized for mobile manipulation. It is electrically powered and hydraulically actuated.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/rVlhMGQgDkY/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=rVlhMGQgDkY'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 2,
        addedBy: {
          uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
          name: 'Amitabh Sharma'
        },
        likes: 0
      }
      ]
    };



        const videoData = {
      videoID: autogeneratedID,
      isSeries: true,
      isActive: true,
      name: 'High Altitude Warfare School | Veer by Discovery',
      description: 'High Altitude Warfare School. Watch the true story of Indian Army Mountain Warriors training to defend the highest battlefield in the world. ',
      URL: {
        thumbnail: 'https://img.youtube.com/vi/rAtJ9PoZ8ng/maxresdefault.jpg',
        video: 'https://www.youtube.com/watch?v=rAtJ9PoZ8ng'
      },
      addedOn: Date.now(),
      views: 0,
      sortOrder: 1,
      addedBy: {
        uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        name: 'Amitabh Sharma'
      },
      likes: 0,
      genre: 'People & Blogs',
      episode: [{
        videoID:  autogeneratedID + '-0',
        name: 'Introduction to High Altitude Warfare School | HAWS E1P1 | Veer by Discovery',
        description: 'The first week of training entails a small walk of about 1.5 km with a little load on one’s back, which soon progresses to 5, 10 and 15 kilograms after two weeks, even as the distance increases and soldiers are introduced to tougher levels.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/bEI7jySEUyQ/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=bEI7jySEUyQ'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 0,
        addedBy: {
        uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        name: 'Amitabh Sharma'
      },
        likes: 0
      },
      {
        videoID:  autogeneratedID + '-1',
        name: 'Mountain Survival Training for Indian Army Soldiers | HAWS E1P2 | Veer by Discovery',
        description: 'Selected Indian Army personnel are trained at HAWS to become mountain warriors. In the initial training, soldiers have to stay in the forest at survival top which is at a height of 10,500 feet. They are trained for survival instincts in bad weather conditions, freezing temperature and low level of oxygen.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/aOOmLTV_Oz8/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=aOOmLTV_Oz8'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 1,
        addedBy: {
        uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        name: 'Amitabh Sharma'
      },
        likes: 0
      },
      {
        videoID:  autogeneratedID + '-2',
        name: 'Stream Crossing Training at High Altitude Warfare School | HAWS E1P3 | Veer by Discovery',
        description: 'During the 72 hours of mountain survival training at High Altitude Warfare School (HAWS) soldiers are trained for combat situations where they have to cross rapid currents of river virtually unaided. Watch India’s fiercest mountain warriors crossing the river stream within minutes. They are among the top instructors at HAWS, representing the nation at the International Army Games of Elbrus in Russia.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/elZiT2RIpFY/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=elZiT2RIpFY'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 2,
        addedBy: {
        uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        name: 'Amitabh Sharma'
      },
        likes: 0
      },
      {
        videoID:  autogeneratedID + '-3',
        name: 'Endurance Run at 9000 Feet | High Altitude Warfare School E1P4 | Veer by Discovery',
        description: 'The Endurance Run at High Altitude Warfare School is an 18km long run in tough terrains with the finish line at a height of 9000 feet. It\'s a mental challenge and endurance test for trainee soldiers at HAWS to run with 18kg of battle load along with their personal weapons. Will they clear the litmus test for the toughest job in the world: defending India’s Himalayan borders. Watch this episode to find out.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/RdFYHrBo5rY/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=RdFYHrBo5rY'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 3,
        addedBy: {
        uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        name: 'Amitabh Sharma'
      },
        likes: 0
      },
      {
        videoID:  autogeneratedID + '-4',
        name: 'Endurance Test: Making of Mountain Warriors | High Altitude Warfare School E1P5 | Veer by Discovery',
        description: 'The Endurance Run at High Altitude Warfare School is an 18km long run in tough terrains with the finish line at a height of 9000 feet. It\'s a mental challenge and endurance test for trainee soldiers at HAWS to run with 18kg of battle load along with their personal weapons. Will they clear the litmus test for the toughest job in the world: defending India’s Himalayan borders. Watch this episode to find out.',
        URL: {
          thumbnail: 'https://img.youtube.com/vi/TB_2e-ydGOI/maxresdefault.jpg',
          video: 'https://www.youtube.com/watch?v=TB_2e-ydGOI'
        },
        addedOn: Date.now(),
        views: 0,
        sortOrder: 5,
        addedBy: {
        uid: 'AyMMm1Y7LrZ0qEKQv7y88wb5hzy1',
        name: 'Amitabh Sharma'
      },
        likes: 0
      }
    ]
    };
*/